### ISSUE TITLE
Flaky test: `AbstractMessageAssertTest$UnhappyPathTests.testHasNotExpiredFailure`

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe-process-test#960] opened 2023-11-07 16:55 UTC
**Description**

Test failed and then succeeded in CI run: https://github.com/camunda/zeebe-process-test/actions/runs/6787134291/job/18449291513?pr=959

```
Warning:  Flakes: 
Warning:  io.camunda.zeebe.process.test.qa.abstracts.assertions.AbstractMessageAssertTest$UnhappyPathTests.testHasNotExpiredFailure
Error:    Run 1: AbstractMessageAssertTest$UnhappyPathTests.testHasNotExpiredFailure:302 
Expecting code to raise a throwable.
[INFO]   Run 2: PASS
```

AssertionError:
```
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.753 s <<< FAILURE! -- in io.camunda.zeebe.process.test.qa.abstracts.assertions.AbstractMessageAssertTest$UnhappyPathTests
[zb-actors-0] INFO io.camunda.zeebe.logstreams.impl.log.Sequencer - Closing sequencer for writing
Error:  io.camunda.zeebe.process.test.qa.abstracts.assertions.AbstractMessageAssertTest$UnhappyPathTests.testHasNotExpiredFailure -- Time elapsed: 0.657 s <<< FAILURE!
[zb-actors-0] INFO io.camunda.zeebe.logstreams - On closing logstream null close 2 readers
java.lang.AssertionError: 

Expecting code to raise a throwable.
	at io.camunda.zeebe.process.test.qa.abstracts.assertions.AbstractMessageAssertTest$UnhappyPathTests.testHasNotExpiredFailure(AbstractMessageAssertTest.java:302)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

I can't find the logs in the [`Unit Test Results macos-latest`](https://github.com/camunda/zeebe-process-test/suites/17983289905/artifacts/1034314325).

**Comment by korthout** [comment] 2023-11-15 14:47
@ana-vinogradova-camunda Please have a look, but time box it. It's okay if we're unable to resolve this now.

**Comment by nicpuppa** [comment] 2023-11-16 14:07
ZPA Mob-Programming:
- We were unable to reproduce the issue
- Why the test fail ? The message was not detected expired
- Why was not detected as expired ? We assert too early and the assertion didn't wait
- Why the assertion didn't wait ? The assertion are not implemented in that way

One solution could be that the user should wait for those cases (using awaitility), but this is annoing on user prespective. Another solution is to implement in the `RecordStream` an await mechanism.

We should investigate more on ZPT project, is not clear if there is already an await mechanism. 

A similar issue was already raised [here](https://github.com/camunda/zeebe-process-test/issues/202#issuecomment-1057734038)

**Comment by ana-vinogradova-camunda** [comment] 2024-01-02 14:47
Run the test for 2000 times, could not reproduce the failure.
(One way to run the test on repeat until failure: `@RepeatedTest(value = 2000, failureThreshold = 1)`)

**Comment by ana-vinogradova-camunda** [comment] 2024-01-16 12:16
Happened again, 2 times.
```
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.018 s <<< FAILURE! -- in io.camunda.zeebe.process.test.qa.abstracts.assertions.AbstractMessageAssertTest$UnhappyPathTests
Error:  io.camunda.zeebe.process.test.qa.abstracts.assertions.AbstractMessageAssertTest$UnhappyPathTests.testHasNotExpiredFailure -- Time elapsed: 0.587 s <<< FAILURE!
java.lang.AssertionError: 

Expecting code to raise a throwable.
	at io.camunda.zeebe.process.test.qa.abstracts.assertions.AbstractMessageAssertTest$UnhappyPathTests.testHasNotExpiredFailure(AbstractMessageAssertTest.java:302)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by korthout** [comment] 2024-01-16 13:18
@ana-vinogradova-camunda I found the reported log in the job's logs:

```
[main] ERROR io.camunda.zeebe.process.test.extension.ZeebeProcessTestExtension - ===== Test failed!
[main] INFO io.camunda.zeebe.process.test.filters.logger.IncidentLogger - 
[main] INFO io.camunda.zeebe.process.test.filters.logger.RecordStreamLogger - 
The following records have been recorded during this test:
| COMMAND             DEPLOYMENT                         CREATE                        | (Processes: [message-event.bpmn])
| EVENT               PROCESS                            CREATED                       | (Process: message-event.bpmn)
| EVENT               DEPLOYMENT                         CREATED                       | 
| COMMAND             MESSAGE                            PUBLISH                       | (Message name: message), (Correlation key: correlationkey), 
| EVENT               MESSAGE                            PUBLISHED                     | (Message name: message), (Correlation key: correlationkey), 
| COMMAND             MESSAGE_BATCH                      EXPIRE                        | (Message Keys: [2251799813685251])
| EVENT               MESSAGE                            EXPIRED                       | (Message name: ), (Correlation key: ), 
```

**Comment by ana-vinogradova-camunda** [comment] 2024-01-18 15:22
ZPA mob programming:

- Tried to reproduce test failure by 'time travelling' and setting `ControlledActorClock` to the date and time when the test failed using the below code:
```
      final OffsetDateTime failingTime =
          OffsetDateTime.of(2024, 1, 16, 12, 9, 12, 650, ZoneOffset.UTC);

      Utilities.increaseTime(engine, Duration.between(OffsetDateTime.now(), failingTime));
```
That leaded to test failures for all dates in the past. It seems these are not the same failures as we had previously, so not helpful for the investigation.
We also verified that the time is increased correctly when we time travel by using the code below:
```
 private void checkSystemTime(final String when)
        throws IllegalAccessException, NoSuchMethodException, InvocationTargetException {
      final Object clock = FieldUtils.readDeclaredField(engine, "clock", true);
      final Instant time =
          (Instant) MethodUtils.invokeMethod(clock, "getCurrentTime", new Object[0]);
      System.out.println(when + " " + time);
    }
```
The sample output would be as follows:
```
Initial time 2024-01-16T12:09:13.237Z
beforeMessageSend 2024-01-16T12:09:13.553Z
afterMessageSent 2024-01-16T12:09:13.676Z
afterTimeIncrease 2024-01-17T12:10:14.781Z
```

- Tried to set Mac time to the date and time when the test last failed (`2024-01-16T12:09:12.0984300Z`). However, the test passed.

Assumptions:
- Rather the message checker is never run or run too early
- Or the message was never expired

Next steps:
- To look at the code for the above described assumptions and try to figure out what could potentially prevent the checker from running or for the message to not get expired.

**Comment by ana-vinogradova-camunda** [comment] 2024-01-30 12:31
Update:

Could not not reproduce the issue. 

Assumptions:
- `MessageTimeToLiveChecker` logic looks correct and  should behave correctly after time increase
- `Utilities.increaseTime()` may swallow timeout exception if the engine takes more than 1 second to adjust to the time change. This might result in message expiration logic to be executed slightly later than expected resulting in assertion failure.

Considering the above reasons the suggestion is to add logging to `Utilities.increaseTime()` as follows (for troubleshooting):
```
  public static void increaseTime(final ZeebeTestEngine engine, final Duration duration)
      throws InterruptedException {
    try {
      waitForIdleState(engine, Duration.ofSeconds(1));
      engine.increaseTime(duration);
      waitForBusyState(engine, Duration.ofSeconds(1));
      waitForIdleState(engine, Duration.ofSeconds(1));
    } catch (final TimeoutException e) {
      // Do nothing. We've waited up to 1 second for processing to start, if it didn't start in this
      // time the engine probably has not got anything left to process.

      // Logging warning for unexpected case when 1 second was not enough
      LOG.warn("Timeout reached after time increase", e);
    }
  }
```

I also suggest logging record stream immediately before the assertion for further troubleshooting (as follows):
```
      // Logging current stream of events for assert troubleshooting
      RecordStream.of(engine.getRecordStreamSource()).print(true);
```

**Comment by berkaycanbc** [comment] 2024-01-30 15:20
@ana-vinogradova-camunda I like the ideas you proposed.

I have couple of additions to be able to correctly spot the issue:

1) Let's log timeout exceptions separately to see on which state it exactly failed.
```java
public static void increaseTime(final ZeebeTestEngine engine, final Duration duration)
      throws InterruptedException {
    try {
      waitForIdleState(engine, Duration.ofSeconds(1));
      engine.increaseTime(duration);
      waitForBusyState(engine, Duration.ofSeconds(1)); // this one
      waitForIdleState(engine, Duration.ofSeconds(1)); // and this one 
    } catch (final TimeoutException e) {
      // Do nothing. We've waited up to 1 second for processing to start, if it didn't start in this
      // time the engine probably has not got anything left to process.

      // Logging warning for unexpected case when 1 second was not enough
      LOG.warn("Timeout reached after time increase", e);
    }
  }
```
2) Let's print records only when assertion fails to prevent unnecessary logging.
3) Let's add link to this issue on top of related changes above, so that we can remove additional loggings once we understand the reason.

Depending on the output of next failure, we will can make changes on how we increase time. 👍

**Comment by ana-vinogradova-camunda** [comment] 2024-01-30 16:09
@berkaycanbc 

Thank you for the suggestions, I agree it is better to log timeout exceptions separately to see on which state it exactly failed👍🏻

Regarding printing records only when assertion fails: my assumption is that there might be the case when the message gets expired between assertion and test extension logging record stream. Example:
- on assertion message is still not expired
-  message expires
- we log the content of record stream

It might be useful to check if that's really the case, what would be your thoughts on that?

**Comment by ana-vinogradova-camunda** [comment] 2024-01-31 14:09
Added logging for further troubleshooting [in this PR](https://github.com/camunda/zeebe-process-test/pull/1056)
Putting it back to the backlog and will wait for the flakiness to happen again.

**Comment by megglos** [comment] 2024-03-11 16:01
closing as it wasn't reported again, please reopen in such a case

**Closed by megglos** 2024-03-11 16:01 UTC
Labels: kind/flake
