### ISSUE TITLE
Support sending signals

### ISSUE THREAD

**Issue by r-herd** [camunda/zeebe-process-test#964] opened 2023-11-09 11:15 UTC
**Description**

Signal events are introduced in camunda 8.3.0. When using the zeebe client to create a new signal event in a @ZeebeProcessTest the following error occurs:

```
io.camunda.zeebe.client.api.command.ClientStatusException
 at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException([ZeebeClientFutureImpl.java:116](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join([ZeebeClientFutureImpl.java:54](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
...
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNKNOWN
 at java.base/java.util.concurrent.CompletableFuture.reportGet([CompletableFuture.java:396](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.base/java.util.concurrent.CompletableFuture.get([CompletableFuture.java:2073](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join([ZeebeClientFutureImpl.java:52](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 ... 72 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
 at io.grpc.Status.asRuntimeException([Status.java:537](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose([ClientCalls.java:481](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
...
```

This issue is for signal events to be supported in zeebe-process-test

**Comment by korthout** [comment] 2023-11-09 11:25
Hi @r-herd 👋 Thanks for raising this!

Could you please provide a reproducible example? That would help us troubleshoot this.

**Comment by r-herd** [comment] 2023-11-09 11:28
This error occurs when executing the following code:
`zeebeClient.newBroadcastSignalCommand().signalName("test").send().join();`

**Comment by korthout** [comment] 2023-11-09 13:20
Thanks @r-herd 👍 

I've given it a try, and I see what's happening. I misread your feature request as a bug. I expected that broadcasting signals was actually already possible, just not supported by zeebe-process-test with assertions. However, it's clear now that actually broadcasting a signal in a zeebe-process-test test case is not supported.

I'll raise this with the team.

**Comment by korthout** [comment] 2023-11-09 13:28
Personal triage:
- issue is a bug, there is no workaround
- priority upcoming, signals are supported since 8.3, and it should be possible to use them in ZPT as well
- this usage does not include signal assertions
- problem might be easily resolved by adding a GrpcResponseMapping entry for broadcast signal + don't assume that variables exist on the broadcast signal request
- we should add some test cases for signal broadcasting to ZPT

@lzgabel Would this be something you could look into? Otherwise, I'll plan something with the team.

**Comment by remcowesterhoud** [comment] 2023-11-09 14:06
I'll pick it up. I'm bored anyways 😄

**Comment by r-herd** [comment] 2023-11-09 14:24
Is there any plan to add assertions for signals soon?

**Closed** 2023-11-09 14:48 UTC
Labels: kind/bug, severity/high

**Comment by remcowesterhoud** [comment] 2023-11-09 16:31
> Is there any plan to add assertions for signals soon?

We haven't planned to add it at this time. I did create an issue for it just now (https://github.com/camunda/zeebe-process-test/issues/971) because I would love to see these assertions as well.

@lzgabel I know you contributed Signals to Zeebe which is awesome. I just wanted to raise awareness for this feature request just in case you'd be interested in contributing it here as well. If you're not that's okay, then we'll pick it up within the team at some point 🙂

**Comment by lzgabel** [comment] 2023-11-09 16:34
💯 @remcowesterhoud Please assign the task to me.
