### ISSUE TITLE
Unable to override ObjectMapper in VariablesMapAssert

### ISSUE THREAD

**Issue by riteshmaurya** [camunda/zeebe-process-test#812] opened 2023-06-29 06:28 UTC
## Description

I want to assert a key with object value which has LocalDateTime as field type in it. 

This is throwing error and asking me add jackson-datatype-jsr310 module in Object mapper.

I am unable to override ObjectMapper provided in VariablesMapAssert.

### Expected behaviour

VariablesMapAssert should allow to provide custom JsonMapper and ObjectMapper.

## Reproduction steps

<details>
<summary>Test code</summary>
    assertions
        .isCompleted()
        .hasPassedElement("requestGroupWorker")
       **.hasVariableWithValue("requestGroup", requestGroupRequest);**

RequestGroup.class having LocalDateTime field

  @JsonProperty("statusUpdatedDate")
  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  private java.time.LocalDateTime statusUpdatedDate;

</details>

<details>
<summary>Error</summary>

Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
	at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3821)
	at io.camunda.zeebe.client.impl.ZeebeObjectMapper.toJson(ZeebeObjectMapper.java:80)

</details>

## Environment

- OS: Linux
- spring-zeebe-test.version=8.0.8

**Comment by remcowesterhoud** [comment] 2023-06-29 07:14
Thanks for reporting! This seems to be duplicate of #724 

As you're using spring-zeebe [this](https://github.com/camunda/zeebe-process-test/issues/724#issuecomment-1499205612) may work for you as a workaround for now.

**Comment by remcowesterhoud** [comment] 2023-07-05 07:55
Individual ZPA triage:
- Feature is requested multiple times now
- Without this it is difficult to test processes using LocalDateTime properly
- I'd like to see this as part of the `8.3` release as it allows users to verify their processes and the developing stage
- Marking it as upcoming and sizing it as small.

**Comment by remcowesterhoud** [comment] 2023-08-18 08:37
@riteshmaurya  Pleased to report that thanks to @nicpuppa this will be available in the 8.3 release 🙂

**Closed by remcowesterhoud** 2023-08-18 08:37 UTC
Labels: kind/bug, area/reliability, area/ux
